export type RowData = {
    name: string,

    bioguide: string,
    lis?: string,
    thomas?: string,
    govtrack?: string,
    opensecrets?: string,
    votesmart?: string,
    fec?: string[],
    cspan?: string,
    wikipedia?: string,
    ballotpedia?: string,
    maplight?: string,
    icpsr?: string,
    house_history?: string,
    wikidata?: string,
    google_entity_id?: string,
    pictorial?: string,

    first?: string,
    last?: string,
    official_full?: string,
    middle?: string,
    nickname?: string,
    suffix?: string,

    birthday?: string,
    gender?: string,

    type?: string,
    start?: string,
    end?: string,
    state?: string,
    district?: number,
    party?: string,
    class?: number,
    url?: string,
    address?: string,
    phone?: string,
    fax?: string,
    contact_form?: string,
    office?: string,
    state_rank?: string,
    rss_url?: string,
    caucus?: string,
    how?: string,
    'end-type'?: string,
    // party_affiliations?: PartyAffiliation[],
    leadership?: string,

    twitter?: string,
    twitter_id?: string,
    facebook?: string,
    youtube?: string,
    youtube_id?: string,
    instagram?: string,
    instagram_id?: string,
    mastodon?: string,
};